name: Deploy na Instância EC2
on:
  workflow_run:
    workflows: ["Criar ou usar Instância EC2 com IP Elástico"]
    types:
      - completed

jobs:
  deploy-na-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Verificar se a instância já existe
      id: checkinstance
      run: |
        existing_instance=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=comentarios-app-instance" --query 'Reservations[].Instances[].[InstanceId]' --output text)
        if [ -z "$existing_instance" ]; then
          echo "::set-output name=instance_exists::false"
        else
          echo "::set-output name=instance_exists::true"
          echo "::set-output name=existing_instance_id::$existing_instance"
        fi

    - name: Copiar arquivos para a instância EC2
      if: steps.checkinstance.outputs.instance_exists == 'true'
      run: |
        
        scp -r * ubuntu@44.232.195.60:/home/ubuntu

    - name: Executar build e deploy na instância EC2
      if: steps.checkinstance.outputs.instance_exists == 'true'
      run: |
        
        ssh ubuntu@44.232.195.60 "cd /home/ubuntu/REMOTE-JOBS-BRAZIL/docker && ./build.sh && ./deploy.sh"
