name: Docker Image CI

on:
  workflow_run:
    workflows: ["Provision Infrastructure"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Print Docker build directory
      run: |
        echo "Docker build directory: $(pwd)"
        ls -al
        
    - name: Build the Docker image
      run: |
        docker build . --file Docker/Dockerfile --tag my-image-name
        docker save my-image-name -o my-image-name.tar

    - name: Debug - List files in current directory
      run: ls -al

    - name: Debug - Display file size of the tarball
      run: du -h my-image-name.tar

    - name: Debug - Display content of the tarball
      run: tar -tvf my-image-name.tar

    - name: Transfer Docker image to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_ELASTIC_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.AWS_PEM }}
        source: my-image-name.tar
        target: /home/ubuntu

    - name: SSH into EC2 instance and run Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_ELASTIC_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo docker load -i /home/ubuntu/my-image-name.tar
          sudo docker run -d --name my-container my-image-name
