name: Docker Image CI

on:
  workflow_run:
    workflows: ["Provision Infrastructure"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    
        
    - name: Build the Docker image
      run: |
        docker build . --file Docker/Dockerfile --tag my-image-name
        docker save my-image-name -o my-image-name.tar
    - name: Print build directory
      run: |
          echo "Build directory: $(pwd)"

    - name: Transfer Docker image to EC2 instance
      run: |
            sudo tar -czf /tmp/my-image-name.tar.gz /home/runner/work/remote-jobs-brazil/remote-jobs-brazil/build/my-image-name.tar
            sudo scp /tmp/my-image-name.tar.gz ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_ELASTIC_IP }}:/home/ubuntu

      

    - name: List files in directory
      run: ls -al

    - name: SSH into EC2 instance and run Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_ELASTIC_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo docker load -i /home/ubuntu/my-image-name.tar
          sudo docker run -d --name my-container my-image-name
