name: Docker 
on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed
jobs:
  install-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Docker is installed
        run: docker --version || echo "Docker not installed"

      - name: Install Docker
        if: ${{ success() }}
        run: |
          sudo yum install -y docker
          sudo service docker start

      - name: Verify Docker installation
        run: docker --version