name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

   
    defaults:
      run:
        shell: bash

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    
    - name: Set up AWS credentials
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-west-2
      # Configura a chave PEM da AWS
    - name: Set up AWS PEM Key
      env:
          AWS_PEM: ${{ secrets.AWS_PEM_KEY }}
      run: |
        echo "$AWS_PEM" | base64 --decode > /tmp/chave.pem
        chmod 400 /tmp/chave.pem
        ls -l /tmp/chave.pem
      
    - name: Use AWS PEM Key
      run: echo "$AWS_PEM" | base64 --decode > chave.pem && chmod 400 chave.pem && ls -l

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve tfplan

