name: Python Build, Test, Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t myapp -f Docker/Dockerfile .
      working-directory: ${{ github.workspace }}

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        docker run myapp python -m pytest
      working-directory: ${{ github.workspace }}

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        docker tag myapp myregistry/myapp
        docker push myregistry/myapp
        # Add any additional deployment steps here
      working-directory: ${{ github.workspace }}
