name: Provision Infrastructure

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Set up AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-west-2

    - name: Set up AWS PEM Key
      run: |
        echo "${{ secrets.AWS_PEM_KEY }}" | base64 --decode > /tmp/chave.pem
        chmod 400 /tmp/chave.pem
        ls -l /tmp/chave.pem

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve tfplan

  docker:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and run Docker container
      run: docker build -t comentarios-app -f docker/Dockerfile ./docker && docker run comentarios-app
